# Generated by Django 4.0.2 on 2022-02-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='43701', max_length=5),
            preserve_default=False,
        ),
    ]
